services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6434:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=sdb
      - POSTGRES_DB=stats-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6433:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15
