spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ewm-db:5432/ewm-main
    username: root
    password: root
  sql:
    init:
      mode: always
stat-server:
  uri: http://stats-server:9090

feign:
  circuitbreaker:
    enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 1
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 1
      automaticTransitionFromOpenToHalfOpenEnabled: true