server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**,
              /users/**/subscriptions/**,
              /users/**/subscribers

        - id: request-service-route
          uri: lb://request-service
          predicates:
            - Path=/users/**/requests/**, /users/**/events/**/requests, /users/**/events/**/requests/**

        - id: event-service-route
          uri: lb://event-service
          predicates:
            - Path=/events/**,
              /users/**/events/**,
              /admin/events/**,
              /categories/**,
              /admin/categories/**,
              /compilations/**,
              /admin/compilations/**

        - id: comment-service-route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**,
              /users/**/comments/**,
              /comments/**