server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**

      routes:
        - id: request-service-route
          uri: lb://request-service
          predicates:
            - Path=/users/**/requests/**, /users/**/events/**/requests, /users/**/events/**/requests/**